#!/bin/bash
# Deployment Helper Script for Alexandria

echo "🚀 Alexandria Deployment Helper"
echo "================================"
echo ""
echo "This script helps you prepare and deploy Alexandria to Vercel + Backend Service"
echo ""
echo "Prerequisites:"
echo "  ✓ Git repository initialized and pushed to GitHub"
echo "  ✓ Vercel account (vercel.com)"
echo "  ✓ Render/Railway/Heroku account"
echo "  ✓ API keys: Google, AssemblyAI, YouTube"
echo ""
echo "Step 1: Deploy Frontend to Vercel"
echo "=================================="
echo ""
echo "Option A: Via GitHub (Recommended)"
echo "  1. Go to https://vercel.com"
echo "  2. Click 'Add New' → 'Project'"
echo "  3. Import your GitHub repo"
echo "  4. Vercel will auto-detect settings"
echo "  5. Add Environment Variables:"
echo "     VITE_API_BASE_URL = https://your-backend-url.com"
echo "  6. Click Deploy"
echo ""
echo "Option B: Via Vercel CLI"
echo "  1. npm install -g vercel"
echo "  2. vercel --prod"
echo ""
echo ""
echo "Step 2: Deploy Backend"
echo "======================"
echo ""
echo "Option A: Deploy to Render (Recommended for Python)"
echo "  1. Go to https://render.com"
echo "  2. Click 'New' → 'Web Service'"
echo "  3. Connect your GitHub repo"
echo "  4. Render will find render.yaml and use it"
echo "  5. Add API keys as environment variables"
echo "  6. Deploy"
echo ""
echo "Option B: Deploy to Railway"
echo "  1. Go to https://railway.app"
echo "  2. New Project → GitHub repo"
echo "  3. Railway auto-detects Python"
echo "  4. Add environment variables"
echo "  5. Deploy"
echo ""
echo "Option C: Deploy via Vercel Serverless (Advanced)"
echo "  1. Create api/ directory with Python handlers"
echo "  2. Use vercel.json to configure routing"
echo "  3. Deploy with Vercel"
echo ""
echo ""
echo "Step 3: Connect Frontend to Backend"
echo "===================================="
echo "  1. Get your backend URL from deployment service"
echo "  2. Go to Vercel Dashboard → Your Project → Settings"
echo "  3. Environment Variables"
echo "  4. Set VITE_API_BASE_URL = https://your-backend-url.com"
echo "  5. Redeploy from Vercel dashboard"
echo ""
echo ""
echo "Step 4: Test"
echo "============"
echo "  1. Open https://your-app.vercel.app"
echo "  2. Try ingesting a YouTube video"
echo "  3. Check browser console for errors"
echo "  4. Verify API calls reach your backend"
echo ""
echo ""
echo "📝 Full guide: See DEPLOYMENT.md"
echo ""
